"""baseline schema

Revision ID: d74b9ba16cb0
Revises: 
Create Date: 2026-09-25 03:46:37.050106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd74b9ba16cb0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_calling_sheet_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('csp_code', sa.String(), nullable=True),
    sa.Column('csp_name', sa.String(), nullable=False),
    sa.Column('csp_email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('circle', sa.String(), nullable=True),
    sa.Column('terminal_status', sa.String(), nullable=True),
    sa.Column('request_type', sa.String(), nullable=True),
    sa.Column('source_message_id', sa.String(), nullable=True),
    sa.Column('source_subject', sa.String(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('is_promoted_to_master', sa.Boolean(), nullable=True),
    sa.Column('promoted_csp_id', sa.Integer(), nullable=True),
    sa.Column('promoted_at', sa.DateTime(), nullable=True),
    sa.Column('extracted_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_calling_sheet_entries_csp_code'), 'auto_calling_sheet_entries', ['csp_code'], unique=False)
    op.create_index(op.f('ix_auto_calling_sheet_entries_csp_email'), 'auto_calling_sheet_entries', ['csp_email'], unique=False)
    op.create_table('ingest_state',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('internal_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('csp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('whatsapp_number', sa.String(), nullable=True),
    sa.Column('current_code', sa.String(), nullable=True),
    sa.Column('lookup_code', sa.String(), nullable=True),
    sa.Column('rm_id', sa.Integer(), nullable=True),
    sa.Column('dc_id', sa.Integer(), nullable=True),
    sa.Column('lho_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('kiosk_location', sa.String(), nullable=True),
    sa.Column('preferred_language', sa.String(), nullable=True),
    sa.Column('calling_sheet_synced_at', sa.DateTime(), nullable=True),
    sa.Column('sheet_row_version', sa.String(), nullable=True),
    sa.Column('is_active_in_calling_sheet', sa.Boolean(), nullable=True),
    sa.Column('has_missing_contact', sa.Boolean(), nullable=True),
    sa.Column('alt_phone', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('circle', sa.String(), nullable=True),
    sa.Column('branch_code', sa.String(), nullable=True),
    sa.Column('terminal_status', sa.String(), nullable=True),
    sa.Column('contact_gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('category_reason', sa.String(), nullable=True),
    sa.Column('category_updated_at', sa.DateTime(), nullable=True),
    sa.Column('next_action_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['dc_id'], ['internal_users.id'], ),
    sa.ForeignKeyConstraint(['lho_id'], ['internal_users.id'], ),
    sa.ForeignKeyConstraint(['rm_id'], ['internal_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('current_code')
    )
    op.create_index(op.f('ix_csp_category'), 'csp', ['category'], unique=False)
    op.create_index(op.f('ix_csp_is_active_in_calling_sheet'), 'csp', ['is_active_in_calling_sheet'], unique=False)
    op.create_index(op.f('ix_csp_lookup_code'), 'csp', ['lookup_code'], unique=True)
    op.create_index(op.f('ix_csp_next_action_at'), 'csp', ['next_action_at'], unique=False)
    op.create_table('agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('csp_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('police_verification_expiry', sa.Date(), nullable=True),
    sa.Column('current_csp_code', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('renewal_status', sa.Enum('DRAFT', 'ACTIVE', 'PENDING_RENEWAL', 'RENEWED', 'EXPIRED_LOCKED', name='renewalstatus'), nullable=False),
    sa.Column('pdf_link', sa.String(), nullable=True),
    sa.Column('pdf_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['csp_id'], ['csp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agreements_csp_id'), 'agreements', ['csp_id'], unique=False)
    op.create_index(op.f('ix_agreements_expiry_date'), 'agreements', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_agreements_police_verification_expiry'), 'agreements', ['police_verification_expiry'], unique=False)
    op.create_table('contact_change_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('csp_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['csp_id'], ['csp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_change_requests_csp_id'), 'contact_change_requests', ['csp_id'], unique=False)
    op.create_table('csp_code_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('csp_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['csp_id'], ['csp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inbound_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_message_id', sa.String(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('email_category', sa.Enum('TERMINAL_RESET', 'TERMINAL_EXTENSION', 'AGREEMENT_DOCUMENT', 'PVR_DOCUMENT', 'CHARACTER_CERTIFICATE', 'IIBF_DOCUMENT', 'GENERAL_CSP_COMMUNICATION', 'UNKNOWN', name='emailcategory'), nullable=True),
    sa.Column('ai_classification_fallback', sa.Boolean(), nullable=True),
    sa.Column('classification_audit', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('sender_on_sheet', sa.Boolean(), nullable=True),
    sa.Column('csp_id', sa.Integer(), nullable=True),
    sa.Column('attachment_decisions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['csp_id'], ['csp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_messages_csp_id'), 'inbound_messages', ['csp_id'], unique=False)
    op.create_index(op.f('ix_inbound_messages_external_message_id'), 'inbound_messages', ['external_message_id'], unique=True)
    op.create_table('portal_tokens',
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('csp_id', sa.Integer(), nullable=False),
    sa.Column('requested_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoke_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['csp_id'], ['csp.id'], ),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index(op.f('ix_portal_tokens_csp_id'), 'portal_tokens', ['csp_id'], unique=False)
    op.create_table('agreement_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('csp_id', sa.Integer(), nullable=True),
    sa.Column('agreement_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('format_version', sa.String(), nullable=True),
    sa.Column('doc_link', sa.String(), nullable=True),
    sa.Column('response_received_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.ForeignKeyConstraint(['csp_id'], ['csp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('csp_id', sa.Integer(), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'EXTRACTED_DETERMINISTIC', 'EXTRACTED_AI', 'NEEDS_APPROVAL', 'VALID', 'NEEDS_REVIEW', 'MANUAL_VERIFIED', 'REJECTED', 'DUPLICATE', 'UNREADABLE', 'EXPIRED', name='documentstatus'), nullable=False),
    sa.Column('extracted_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('upload_channel', sa.String(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('validity_rule_used', sa.String(), nullable=True),
    sa.Column('has_explicit_3year_clause', sa.Boolean(), nullable=True),
    sa.Column('iibf_reg_number', sa.String(), nullable=True),
    sa.Column('field_confidences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('holder_name', sa.String(), nullable=True),
    sa.Column('validity_months', sa.Integer(), nullable=True),
    sa.Column('date_source', sa.String(), nullable=True),
    sa.Column('readability', sa.String(), nullable=True),
    sa.Column('source_message_id', sa.String(), nullable=True),
    sa.Column('source_date', sa.DateTime(), nullable=True),
    sa.Column('sender_on_sheet', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.ForeignKeyConstraint(['csp_id'], ['csp.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('csp_id', 'sha256', name='uq_document_csp_hash')
    )
    op.create_index(op.f('ix_documents_csp_id'), 'documents', ['csp_id'], unique=False)
    op.create_index(op.f('ix_documents_expiry_date'), 'documents', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_documents_iibf_reg_number'), 'documents', ['iibf_reg_number'], unique=False)
    op.create_index(op.f('ix_documents_is_current'), 'documents', ['is_current'], unique=False)
    op.create_index(op.f('ix_documents_issue_date'), 'documents', ['issue_date'], unique=False)
    op.create_index(op.f('ix_documents_readability'), 'documents', ['readability'], unique=False)
    op.create_index(op.f('ix_documents_sha256'), 'documents', ['sha256'], unique=False)
    op.create_index(op.f('ix_documents_source_message_id'), 'documents', ['source_message_id'], unique=False)
    op.create_table('escalations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('escalated_to', sa.Integer(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.ForeignKeyConstraint(['escalated_to'], ['internal_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_agreement_id'), 'escalations', ['agreement_id'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=True),
    sa.Column('delivery_status', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_agreement_id'), 'reminders', ['agreement_id'], unique=False)
    op.create_index(op.f('ix_reminders_idempotency_key'), 'reminders', ['idempotency_key'], unique=True)
    op.create_table('extraction_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('ai_value', sa.String(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('human_value', sa.String(), nullable=True),
    sa.Column('corrected_by', sa.Integer(), nullable=True),
    sa.Column('corrected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['corrected_by'], ['internal_users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manual_review_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'CORRECTED', 'REJECTED', name='reviewstatus'), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('correction_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['internal_users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outreach_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('csp_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('ladder', sa.String(), nullable=False),
    sa.Column('anchor_date', sa.Date(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('close_reason', sa.String(), nullable=True),
    sa.Column('csp_messages', sa.Integer(), nullable=False),
    sa.Column('rm_messages', sa.Integer(), nullable=False),
    sa.Column('dc_messages', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['csp_id'], ['csp.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_cycles_csp_id'), 'outreach_cycles', ['csp_id'], unique=False)
    op.create_index('uq_open_cycle', 'outreach_cycles', ['csp_id', 'document_type', 'kind'], unique=True, postgresql_where=sa.text('closed_at IS NULL'))
    op.create_table('outbound_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('csp_id', sa.Integer(), nullable=True),
    sa.Column('template_name', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'QUEUED_FOR_REVIEW', 'APPROVED', 'SENT', 'FAILED', 'REJECTED', 'READY_NOT_SENT', 'BLOCKED', name='outboundstatus'), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('recipient_role', sa.String(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('provider_message_id', sa.String(), nullable=True),
    sa.Column('delivery_status', sa.String(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['csp_id'], ['csp.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['outreach_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_messages_csp_id'), 'outbound_messages', ['csp_id'], unique=False)
    op.create_index(op.f('ix_outbound_messages_cycle_id'), 'outbound_messages', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_outbound_messages_idempotency_key'), 'outbound_messages', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbound_messages_idempotency_key'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_cycle_id'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_csp_id'), table_name='outbound_messages')
    op.drop_table('outbound_messages')
    op.drop_index('uq_open_cycle', table_name='outreach_cycles', postgresql_where=sa.text('closed_at IS NULL'))
    op.drop_index(op.f('ix_outreach_cycles_csp_id'), table_name='outreach_cycles')
    op.drop_table('outreach_cycles')
    op.drop_table('manual_review_queue')
    op.drop_table('extraction_corrections')
    op.drop_index(op.f('ix_reminders_idempotency_key'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_agreement_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_escalations_agreement_id'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_index(op.f('ix_documents_source_message_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_readability'), table_name='documents')
    op.drop_index(op.f('ix_documents_issue_date'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_current'), table_name='documents')
    op.drop_index(op.f('ix_documents_iibf_reg_number'), table_name='documents')
    op.drop_index(op.f('ix_documents_expiry_date'), table_name='documents')
    op.drop_index(op.f('ix_documents_csp_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('agreement_events')
    op.drop_index(op.f('ix_portal_tokens_csp_id'), table_name='portal_tokens')
    op.drop_table('portal_tokens')
    op.drop_index(op.f('ix_inbound_messages_external_message_id'), table_name='inbound_messages')
    op.drop_index(op.f('ix_inbound_messages_csp_id'), table_name='inbound_messages')
    op.drop_table('inbound_messages')
    op.drop_table('csp_code_history')
    op.drop_index(op.f('ix_contact_change_requests_csp_id'), table_name='contact_change_requests')
    op.drop_table('contact_change_requests')
    op.drop_index(op.f('ix_agreements_police_verification_expiry'), table_name='agreements')
    op.drop_index(op.f('ix_agreements_expiry_date'), table_name='agreements')
    op.drop_index(op.f('ix_agreements_csp_id'), table_name='agreements')
    op.drop_table('agreements')
    op.drop_index(op.f('ix_csp_next_action_at'), table_name='csp')
    op.drop_index(op.f('ix_csp_lookup_code'), table_name='csp')
    op.drop_index(op.f('ix_csp_is_active_in_calling_sheet'), table_name='csp')
    op.drop_index(op.f('ix_csp_category'), table_name='csp')
    op.drop_table('csp')
    op.drop_table('internal_users')
    op.drop_table('ingest_state')
    op.drop_index(op.f('ix_auto_calling_sheet_entries_csp_email'), table_name='auto_calling_sheet_entries')
    op.drop_index(op.f('ix_auto_calling_sheet_entries_csp_code'), table_name='auto_calling_sheet_entries')
    op.drop_table('auto_calling_sheet_entries')
    # ### end Alembic commands ###
